version: '3'

services:
  db:
    image: db:latest
    container_name: db
    environment:
      POSTGRES_DB: flight_booking_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      DB_SCHEMA: flight_booking_schema
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: test -f /tmp/db_ready
      retries: 100
volumes:
  db:
    driver: local
